#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 YUki Sato s21C1056FY@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += float(line)
    except:
        ans += float(line)

print(ans)     
